### DISCUSSION TITLE
Fresh install. Stable Diffusion CUDA Error

### DISCUSSION THREAD

**Discussion by mickyyman** [LykosAI/StabilityMatrix#1299] [Q&A] [answered]
Hi,

I'm terribly sorry if this is the wrong place to ask but I'm a complete loss. Ever since I got a 5080 GPU i cannot get passed the CUDA error no matter what I try.

I'm hoping some can show some insight as the why this is happening (and this is happening with all other GUI's etc as well).

I do notice some warnings but i do seem to have the proper pytorch and cuda version (i think?)

The log I keep on seeing:

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-665-gae278f79
Commit hash: ae278f794069a69b79513e16207efc7f1ffdf406
L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\extensions-builtin\forge_legacy_preprocessors\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --gradio-allowed-path 'L:\StabilityMatrix\Images'
L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\torch\cuda\__init__.py:209: UserWarning: 
NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
Total VRAM 16303 MB, total RAM 31861 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 5080 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\models\ControlNetPreprocessor
2025-06-16 18:58:29,461 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'L:\\StabilityMatrix\\Packages\\stable-diffusion-webui-forge\\models\\Stable-diffusion\\sd\\dreamshaper_8.safetensors', 'hash': '9d40847d'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.0s (prepare environment: 2.7s, launcher: 0.3s, import torch: 4.4s, initialize shared: 0.1s, other imports: 0.2s, load scripts: 1.3s, create ui: 1.3s, gradio launch: 0.6s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 93.72% GPU memory (15278.00 MB) to load weights, and use 6.28% GPU memory (1024.00 MB) to do matrix computation.
Loading Model: {'checkpoint_info': {'filename': 'L:\\StabilityMatrix\\Packages\\stable-diffusion-webui-forge\\models\\Stable-diffusion\\sd\\dreamshaper_8.safetensors', 'hash': '9d40847d'}, 'additional_modules': [], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'unet': 686, 'vae': 248, 'text_encoder': 197, 'ignore': 0}
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
Model loaded in 0.5s (unload existing model: 0.2s, forge model load: 0.3s).
[Unload] Trying to free 1329.14 MB for cuda:0 with 0 models keep loaded ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 14854.90 MB, Model Require: 234.72 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 13596.18 MB, All loaded to GPU.
Moving model(s) has taken 0.11 seconds
Traceback (most recent call last):
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\txt2img.py", line 131, in txt2img_function
    processed = processing.process_images(p)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\processing.py", line 842, in process_images
    res = process_images_inner(p)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\processing.py", line 962, in process_images_inner
    p.setup_conds()
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\processing.py", line 1601, in setup_conds
    super().setup_conds()
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\processing.py", line 503, in setup_conds
    self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, total_steps, [self.cached_uc], self.extra_network_data)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\processing.py", line 474, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps, hires_steps, shared.opts.use_old_scheduling)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\modules\prompt_parser.py", line 189, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\backend\diffusion_engine\sd15.py", line 66, in get_learned_conditioning
    cond = self.text_processing_engine(prompt)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\backend\text_processing\classic_engine.py", line 272, in __call__
    z = self.process_tokens(tokens, multipliers)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\backend\text_processing\classic_engine.py", line 305, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\backend\text_processing\classic_engine.py", line 128, in encode_with_transformers
    self.text_encoder.transformer.text_model.embeddings.position_embedding = self.text_encoder.transformer.text_model.embeddings.position_embedding.to(dtype=torch.float32)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
  File "L:\StabilityMatrix\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Any help is much appreciated!

Kind regards.

**Comment by mohnjiles** [comment, marked as answer]
Hi, you can update torch from SM packages tab -> 3-dots menu for forge -> python packages -> + button -> enter
```torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu128 --force-reinstall```

then click OK and once that's done it should be all set.

Also double check that you're on the latest version of Stability Matrix in the Settings tab, should be v2.14.2, to make sure this doesn't happen again after an update to forge.

**Comment by mickyyman** [comment]
That did the trick. Thank you so much!
