### ISSUE TITLE
After installing it fails to work. Incorrect Pytorch.

### ISSUE THREAD

**Issue by SamanthaRoxx** [LykosAI/StabilityMatrix#1344]
### What happened?

During first time run it says "NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90."
Then if you try to generate anything it says "RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions."
I have latest pytorch installed globally and comfyui and other image/video programs work fine.

I have pytorch 2.9.0 and CUDA 12.9. 

### Relevant logs

```shell

```

### Version

2.14.3

### What Operating System are you using?

Windows

**Comment by SamanthaRoxx** [comment]
Anyone else having this issue... find the \app\venv\Scripts directory and use the following two commands. Worked for me:
python.exe -s -m pip install --pre --upgrade --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/nightly/cu128
python.exe -s -m pip install --pre --upgrade --no-cache-dir torchvision --extra-index-url https://download.pytorch.org/whl/nightly/cu128

**Comment by Hawkeye131** [comment]
> Anyone else having this issue... find the \app\venv\Scripts directory and use the following two commands. Worked for me: python.exe -s -m pip install --pre --upgrade --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/nightly/cu128 python.exe -s -m pip install --pre --upgrade --no-cache-dir torchvision --extra-index-url https://download.pytorch.org/whl/nightly/cu128

I am having the same issue but when I try to run the above commands I get 

"Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Apps > Advanced app settings > App execution aliases" 


I am big dumb and ran in power-shell not cmd 


In other news on start up it does says 

D:\Stability4\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\torchvision\io\image.py:14: UserWarning: Failed to load image Python extension: 'Could not load this library: D:\Stability4\Packages\stable-diffusion-webui-forge\venv\Lib\site-packages\torchvision\image.pyd'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?

idk that prob does not help.
