### ISSUE TITLE
How fix error with 5000 series(Blackwell) Cuda 13.00 [my gpu GeForce RTX 5070 Ti]

### ISSUE THREAD

**Issue by Enderkiller5532** [LykosAI/StabilityMatrix#1360]
### What happened?

First of all that my first time when i try help people with it so sorry if it have mistakes.
So when you install StabilityMatrix  it support 4000 series and other but 5000 not. PyTorch(problem)
## Fix it with this commands (archlinux for other same but different location)
```
cd /opt/stabilitymatrix/Data/Packages/stable-diffusion-webui/venv

```
#### That is location of virtual env that use matrix.
```
./bin/pip install --pre --upgrade --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/nightly/cu128
```
#### That command will install cu128 to your virtual env.

So yea all versions of 50 series have this problem now.
ps:And remember that on many linux distros venv may be in my location or other so ye check before run commands (or it on main env).
pss: if it still have problem use ``` --skip-torch-cuda-test ``` to test after fixing.
psss: if it still have problem you can try this(i don't really test it so use it at your own risk):
```
pip install --pre --upgrade --no-cache-dir xformers --extra-index-url https://download.pytorch.org/whl/nightly/cu128
```
pssss:And if it don't generate image you can use(in venv dir*):
```
./bin/pip uninstall -y fastapi starlette       
./bin/pip install "fastapi==0.95.2" "starlette==0.27.0"
```
Sorry for that but you may have to use 'skip install'. 
And stay safe.

# All list of gpu that may have problem

    GeForce RTX 5050
    GeForce RTX 5060
    GeForce RTX 5060 Ti (8GB)
    GeForce RTX 5060 Ti (16GB)
    GeForce RTX 5070
    GeForce RTX 5070 Ti
    GeForce RTX 5080
    GeForce RTX 5090

# OS Archlinux 
## What can help to debug 
```
nvidia-smi
```
[pytorch install commands](https://pytorch.org/get-started/locally/)

### Steps to reproduce

1. Install StabilityMatrix
```
 yay -S (stabilitymatrix-git/stabilitymatrix/stabilitymatrix-bin)
```
2. install webui (my situation stable diffusion web ui )
3. Start webui get error {RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.}

### Relevant logs

```shell
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
```

### Version

v2.14.3

### What Operating System are you using?

Linux

**Comment by Enderkiller5532** [comment]
I hope that will help and ye i will close this issue if nobody will have problems(but later).

**Comment by 1265775896** [comment]
**Didn't work, But figured out another method**

**Environment:**

- Archlinux
- GeForce RTX 5060
- Stable Diffusion WebUI Forge

**Reproduce**

- Same as above, Until execute

```shell
cd /opt/stabilitymatrix/Data/Packages/stable-diffusion-webui/venv
./bin/pip install --pre --upgrade --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/nightly/cu128
``` 

- Error

```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-clip-torch 2.20.0 requires protobuf<4, but you have protobuf 4.25.8 which is incompatible.
torchvision 0.18.1+cu121 requires torch==2.3.1, but you have torch 2.9.0.dev20250831+cu128 which is incompatible.
``` 

**Fix**

```shell
./bin/pip install torchvision==0.23.0+cu128 --extra-index-url https://download.pytorch.org/whl/cu128
``` 

This works for me, hope it helps.
