### ISSUE TITLE
Fresh Install: Stability Matrix + Stable Diffusion WebUI Forge Neo - PyTorch error ??

### ISSUE THREAD

**Issue by csanii123** [LykosAI/StabilityMatrix#1648]
### What happened?

I followed these steps:

Installed Stability Matrix v2.15.8 -> no issues
Ran Stability Matrix and installed Stable Diffusion WebUI Forge Neo -> no issues
Started Stable Diffusion and in the console it gave a PyTorch version error for my gfx card but the error doesn't make sense to me as it tells me I need to change the PyTorch version to v12.6 but says the existing version supports versions between 12 and 13 ???
Please note that Stable Diffusion does start in the browser but since PyTorch can't see my gfx card properly it doesn't really allow me to do anything.

Am I misunderstanding the error message or is there a bug in the error code given ?
Any help to fix the issue would be much appreciated.

EXTRACT FROM CONSOLE
Python 3.13.12 (main, Feb 3 2026, 22:53:26) [MSC v.1944 64 bit (AMD64)] Version: neo Launching Web UI with arguments: --skip-python-version-check --gradio-allowed-path 'J:\LLM_Directory\Images' J:\LLM_Directory\Packages\forge-neo\venv\Lib\site-packages\torch\cuda_init_.py:371: UserWarning: Found GPU0 NVIDIA GeForce GTX 1070 Ti which is of compute capability (CC) 6.1. The following list shows the CCs this version of PyTorch was built for and the hardware CCs it supports:
• 7.5 which supports hardware CC >=7.5,<8.0
• 8.0 which supports hardware CC >=8.0,<9.0 except {8.7}
• 8.6 which supports hardware CC >=8.6,<9.0 except {8.7}
• 9.0 which supports hardware CC >=9.0,<10.0
• 10.0 which supports hardware CC >=10.0,<11.0 except {10.1}
• 12.0 which supports hardware CC >=12.0,<13.0 Please follow the instructions at https://pytorch.org/get-started/locally/ to install a PyTorch release that supports one of these CUDA versions: 12.6 warn_unsupported_code(d, device_cc, code_ccs) J:\LLM_Directory\Packages\forge-neo\venv\Lib\site-packages\torch\cuda_init.py:489: UserWarning: NVIDIA GeForce GTX 1070 Ti with CUDA capability sm_61 is not compatible with the current PyTorch installation. The current PyTorch install supports CUDA capabilities sm_75 sm_80 sm_86 sm_90 sm_100 sm_120. If you want to use the NVIDIA GeForce GTX 1070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

### Steps to reproduce

1 - Run Stability Matrix 
2 - Select Stable Diffusion and LAUNCH
3 - Log shows error but Stable Diffusion web page opens but is unable to GENERATE as PyTorch version "wrong" for gfx card.

The error doesn't make sense as it says I need to change the PyTorch version to v12.6 but says the existing version supports versions between 12 and 13 ???

### Relevant logs

```shell
Python 3.13.12 (main, Feb 3 2026, 22:53:26) [MSC v.1944 64 bit (AMD64)] Version: neo Launching Web UI with arguments: --skip-python-version-check --gradio-allowed-path 'J:\LLM_Directory\Images' J:\LLM_Directory\Packages\forge-neo\venv\Lib\site-packages\torch\cuda_init_.py:371: UserWarning: Found GPU0 NVIDIA GeForce GTX 1070 Ti which is of compute capability (CC) 6.1. The following list shows the CCs this version of PyTorch was built for and the hardware CCs it supports:
• 7.5 which supports hardware CC >=7.5,<8.0
• 8.0 which supports hardware CC >=8.0,<9.0 except {8.7}
• 8.6 which supports hardware CC >=8.6,<9.0 except {8.7}
• 9.0 which supports hardware CC >=9.0,<10.0
• 10.0 which supports hardware CC >=10.0,<11.0 except {10.1}
• 12.0 which supports hardware CC >=12.0,<13.0 Please follow the instructions at https://pytorch.org/get-started/locally/ to install a PyTorch release that supports one of these CUDA versions: 12.6 warn_unsupported_code(d, device_cc, code_ccs) J:\LLM_Directory\Packages\forge-neo\venv\Lib\site-packages\torch\cuda_init.py:489: UserWarning: NVIDIA GeForce GTX 1070 Ti with CUDA capability sm_61 is not compatible with the current PyTorch installation. The current PyTorch install supports CUDA capabilities sm_75 sm_80 sm_86 sm_90 sm_100 sm_120. If you want to use the NVIDIA GeForce GTX 1070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```

### Version

v2.15.8

### What Operating System are you using?

Windows

**Comment by NeuralFault** [comment]
This is likely due to Forge Neo's internal PyTorch installation logic.

For GTX 10 series you need to install a Pytorch installation thats built against CUDA 12.6  (which is the 12.6 its mentioning)
As Pytorch dropped further support for Pre-RTX GPUs with their cu128 builds and newer.

Go to 3dot menu for Forge Neo in SM Packages Tab > Python Packages > click + button and paste this in after the "pip install":

torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126 --force-reinstall

-----

After that completes go into the Launch Options and set `--skip-install` to prevent chance of Neo from overwriting it.
SM's internal install logic for packages does a hardware check and if you have below RTX, then it does install with cu126 build of pytorch... its just Neo also does it's own pytorch install management internally and it defaults to using the cu128 build (for Modern Nvidia GPUs).

**Comment by csanii123** [comment]
THANK YOU!!!!
That solved the problem for me so I can now use Stable Diffusion to create images.
Please note that the error message says I need PyTorch v12.6 but also says the existing installed version supports hardware CC >=12.0,<13.0 - I think the error message is misleading since 12.0 < 12.6 < 13.0

Thanks for the help.

**Comment by NeuralFault** [comment]
It's referring to CUDA versions, not pytorch versions.

CUDA supports your GPU between CUDA 12.0 and 12.9, Nvidia dropped further support for it with CUDA on release of 13.0.
Pytorch themselves dropped it earlier with their cu128 (CUDA 12.8) builds.

That error is actually correct, its specifically talking about cuda versions. (Greater than or equal to Cuda 12.0, and less than Cuda 13.0)

**Comment by csanii123** [comment]
That makes a lot more sense. Thanks for the clarification.
