### ISSUE TITLE
[BUG] Can't install Fooocus in "CPU Only" =>"AssertionError: Torch not compiled with CUDA enabled"

### ISSUE THREAD

**Issue by Giribot** [LykosAI/StabilityMatrix#819]
Hello !

I try to install Fooocus 2.5.5 with Stability Matrix 2.11.6 in "CPU ONLY" mode: it doesn't work now.....

```
[System ARGV] ['C:\\Users\\ribotg\\Desktop\\Dossiers\\StabilityMatrix-win-x64\\Data\\Packages\\Fooocus\\launch.py', '--disable-xformers']
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.5.5
[Cleanup] Attempting to delete content of temp dir C:\Users\ribotg\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin" to C:\Users\ribotg\Desktop\Dossiers\StabilityMatrix-win-x64\Data\Packages\Fooocus\models\prompt_expansion\fooocus_expansion\pytorch_model.bin

100%|██████████| 335M/335M [00:32<00:00, 10.9MB/s]
Traceback (most recent call last):
  File "C:\Users\ribotg\Desktop\Dossiers\StabilityMatrix-win-x64\Data\Packages\Fooocus\launch.py", line 152, in <module>
    from webui import *
  File "C:\Users\ribotg\Desktop\Dossiers\StabilityMatrix-win-x64\Data\Packages\Fooocus\webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "C:\Users\ribotg\Desktop\Dossiers\StabilityMatrix-win-x64\Data\Packages\Fooocus\modules\async_worker.py", line 3, in <module>
    from extras.inpaint_mask import generate_mask_from_image, SAMOptions
  File "C:\Users\ribotg\Desktop\Dossiers\StabilityMatrix-win-x64\Data\Packages\Fooocus\extras\inpaint_mask.py", line 6, in <module>
    from extras.GroundingDINO.util.inference import default_groundingdino
  File "C:\Users\ribotg\Desktop\Dossiers\StabilityMatrix-win-x64\Data\Packages\Fooocus\extras\GroundingDINO\util\inference.py", line 3, in <module>
    import ldm_patched.modules.model_management as model_management
  File "C:\Users\ribotg\Desktop\Dossiers\StabilityMatrix-win-x64\Data\Packages\Fooocus\ldm_patched\modules\model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\ribotg\Desktop\Dossiers\StabilityMatrix-win-x64\Data\Packages\Fooocus\ldm_patched\modules\model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\ribotg\Desktop\Dossiers\StabilityMatrix-win-x64\Data\Packages\Fooocus\venv\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\ribotg\Desktop\Dossiers\StabilityMatrix-win-x64\Data\Packages\Fooocus\venv\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```
the stability matrix installation of Fooocus is paused for the installation of Visual Basic, I type my password requested by Windows to continue, and the installation continues........ But when I launch Fooocus on Stability matrix, I have this error.....

**Comment by SpoiledCoding** [comment]
It seems like StabilityMatrix hallucinates and gets stuck thinking we have an Nvidia card installed. It starts installing / updating the packages with that support in mind. I've been having this issue on Ubuntu 22.04 with a 7900XTX when I try to install ComfyUI.

Despite being set to 'rocm', the pytorch version installed is the CUDA one, along with a bunch of Nvidia packages.

Something that worked for me was: Outside of my StabilityMatrix folder, followed the ComfyUI install instructions from their [GitHub](https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#manual-install-windows-linux).

Installed the pip requirements into a venv environment and linked to it from StabilityMatrix's ComfyUi folder.
